name: g2p
channels:
  - conda-forge
  - defaults
dependencies:
  # 核心依赖
  - python=3.8
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - scipy>=1.7.0

  # 机器学习模型
  - xgboost>=1.6.0
  - lightgbm>=3.3.0

  # 数据处理和可视化
  - matplotlib>=3.4.0
  - seaborn>=0.11.0

  # 工具包
  - tqdm>=4.62.0
  - joblib>=1.0.0

  # PyTorch GPU 版本（CUDA 11.7）
  - pytorch=2.0.0
  - cudatoolkit=11.7

  # pip 依赖
  - pip
  - pip:
      - cyvcf2>=0.30.0

# 可选：如需指定 pip 包
#  - pip:
#      - some_pip_only_package